// Generated by gencpp from file ros_define_data/grasp_Request.msg
// DO NOT EDIT!


#ifndef ROS_DEFINE_DATA_MESSAGE_GRASP_REQUEST_H
#define ROS_DEFINE_DATA_MESSAGE_GRASP_REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_define_data
{
template <class ContainerAllocator>
struct grasp_Request_
{
  typedef grasp_Request_<ContainerAllocator> Type;

  grasp_Request_()
    : x(0)
    , y(0)  {
    }
  grasp_Request_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint16_t _x_type;
  _x_type x;

   typedef uint16_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::ros_define_data::grasp_Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_define_data::grasp_Request_<ContainerAllocator> const> ConstPtr;

}; // struct grasp_Request_

typedef ::ros_define_data::grasp_Request_<std::allocator<void> > grasp_Request;

typedef boost::shared_ptr< ::ros_define_data::grasp_Request > grasp_RequestPtr;
typedef boost::shared_ptr< ::ros_define_data::grasp_Request const> grasp_RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_define_data::grasp_Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_define_data::grasp_Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_define_data::grasp_Request_<ContainerAllocator1> & lhs, const ::ros_define_data::grasp_Request_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_define_data::grasp_Request_<ContainerAllocator1> & lhs, const ::ros_define_data::grasp_Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_define_data

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_define_data::grasp_Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_define_data::grasp_Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_define_data::grasp_Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_define_data::grasp_Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_define_data::grasp_Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_define_data::grasp_Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_define_data::grasp_Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b80853b9dd76da1c3efb4dbc2426fe9";
  }

  static const char* value(const ::ros_define_data::grasp_Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b80853b9dd76da1ULL;
  static const uint64_t static_value2 = 0xc3efb4dbc2426fe9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_define_data::grasp_Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_define_data/grasp_Request";
  }

  static const char* value(const ::ros_define_data::grasp_Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_define_data::grasp_Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request\n"
"uint16 x\n"
"uint16 y\n"
;
  }

  static const char* value(const ::ros_define_data::grasp_Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_define_data::grasp_Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grasp_Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_define_data::grasp_Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_define_data::grasp_Request_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_DEFINE_DATA_MESSAGE_GRASP_REQUEST_H
