// Generated by gencpp from file ros_define_data/grasp_Response.msg
// DO NOT EDIT!


#ifndef ROS_DEFINE_DATA_MESSAGE_GRASP_RESPONSE_H
#define ROS_DEFINE_DATA_MESSAGE_GRASP_RESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_define_data
{
template <class ContainerAllocator>
struct grasp_Response_
{
  typedef grasp_Response_<ContainerAllocator> Type;

  grasp_Response_()
    : distance(0)  {
    }
  grasp_Response_(const ContainerAllocator& _alloc)
    : distance(0)  {
  (void)_alloc;
    }



   typedef uint16_t _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::ros_define_data::grasp_Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_define_data::grasp_Response_<ContainerAllocator> const> ConstPtr;

}; // struct grasp_Response_

typedef ::ros_define_data::grasp_Response_<std::allocator<void> > grasp_Response;

typedef boost::shared_ptr< ::ros_define_data::grasp_Response > grasp_ResponsePtr;
typedef boost::shared_ptr< ::ros_define_data::grasp_Response const> grasp_ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_define_data::grasp_Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_define_data::grasp_Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_define_data::grasp_Response_<ContainerAllocator1> & lhs, const ::ros_define_data::grasp_Response_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_define_data::grasp_Response_<ContainerAllocator1> & lhs, const ::ros_define_data::grasp_Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_define_data

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_define_data::grasp_Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_define_data::grasp_Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_define_data::grasp_Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_define_data::grasp_Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_define_data::grasp_Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_define_data::grasp_Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_define_data::grasp_Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4db6e4febd2342355b86e2b5ee754faf";
  }

  static const char* value(const ::ros_define_data::grasp_Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4db6e4febd234235ULL;
  static const uint64_t static_value2 = 0x5b86e2b5ee754fafULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_define_data::grasp_Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_define_data/grasp_Response";
  }

  static const char* value(const ::ros_define_data::grasp_Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_define_data::grasp_Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response\n"
"uint16 distance\n"
"\n"
;
  }

  static const char* value(const ::ros_define_data::grasp_Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_define_data::grasp_Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grasp_Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_define_data::grasp_Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_define_data::grasp_Response_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_DEFINE_DATA_MESSAGE_GRASP_RESPONSE_H
