// Generated by gencpp from file ros_define_data/grasp_.msg
// DO NOT EDIT!


#ifndef ROS_DEFINE_DATA_MESSAGE_GRASP__H
#define ROS_DEFINE_DATA_MESSAGE_GRASP__H

#include <ros/service_traits.h>


#include <ros_define_data/grasp_Request.h>
#include <ros_define_data/grasp_Response.h>


namespace ros_define_data
{

struct grasp_
{

typedef grasp_Request Request;
typedef grasp_Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct grasp_
} // namespace ros_define_data


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_define_data::grasp_ > {
  static const char* value()
  {
    return "4de6ef4ba77ca302deb19b408e53f740";
  }

  static const char* value(const ::ros_define_data::grasp_&) { return value(); }
};

template<>
struct DataType< ::ros_define_data::grasp_ > {
  static const char* value()
  {
    return "ros_define_data/grasp_";
  }

  static const char* value(const ::ros_define_data::grasp_&) { return value(); }
};


// service_traits::MD5Sum< ::ros_define_data::grasp_Request> should match
// service_traits::MD5Sum< ::ros_define_data::grasp_ >
template<>
struct MD5Sum< ::ros_define_data::grasp_Request>
{
  static const char* value()
  {
    return MD5Sum< ::ros_define_data::grasp_ >::value();
  }
  static const char* value(const ::ros_define_data::grasp_Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_define_data::grasp_Request> should match
// service_traits::DataType< ::ros_define_data::grasp_ >
template<>
struct DataType< ::ros_define_data::grasp_Request>
{
  static const char* value()
  {
    return DataType< ::ros_define_data::grasp_ >::value();
  }
  static const char* value(const ::ros_define_data::grasp_Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_define_data::grasp_Response> should match
// service_traits::MD5Sum< ::ros_define_data::grasp_ >
template<>
struct MD5Sum< ::ros_define_data::grasp_Response>
{
  static const char* value()
  {
    return MD5Sum< ::ros_define_data::grasp_ >::value();
  }
  static const char* value(const ::ros_define_data::grasp_Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_define_data::grasp_Response> should match
// service_traits::DataType< ::ros_define_data::grasp_ >
template<>
struct DataType< ::ros_define_data::grasp_Response>
{
  static const char* value()
  {
    return DataType< ::ros_define_data::grasp_ >::value();
  }
  static const char* value(const ::ros_define_data::grasp_Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_DEFINE_DATA_MESSAGE_GRASP__H
