// Generated by gencpp from file ros_define_data/grasp.msg
// DO NOT EDIT!


#ifndef ROS_DEFINE_DATA_MESSAGE_GRASP_H
#define ROS_DEFINE_DATA_MESSAGE_GRASP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_define_data
{
template <class ContainerAllocator>
struct grasp_
{
  typedef grasp_<ContainerAllocator> Type;

  grasp_()
    : x(0)
    , y(0)
    , z(0.0)
    , angle(0.0)
    , width(0.0)  {
    }
  grasp_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0.0)
    , angle(0.0)
    , width(0.0)  {
  (void)_alloc;
    }



   typedef uint16_t _x_type;
  _x_type x;

   typedef uint16_t _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _angle_type;
  _angle_type angle;

   typedef double _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::ros_define_data::grasp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_define_data::grasp_<ContainerAllocator> const> ConstPtr;

}; // struct grasp_

typedef ::ros_define_data::grasp_<std::allocator<void> > grasp;

typedef boost::shared_ptr< ::ros_define_data::grasp > graspPtr;
typedef boost::shared_ptr< ::ros_define_data::grasp const> graspConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_define_data::grasp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_define_data::grasp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_define_data::grasp_<ContainerAllocator1> & lhs, const ::ros_define_data::grasp_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.angle == rhs.angle &&
    lhs.width == rhs.width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_define_data::grasp_<ContainerAllocator1> & lhs, const ::ros_define_data::grasp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_define_data

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_define_data::grasp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_define_data::grasp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_define_data::grasp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_define_data::grasp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_define_data::grasp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_define_data::grasp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_define_data::grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abc3897fa241af8b047640ec48eaf40f";
  }

  static const char* value(const ::ros_define_data::grasp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabc3897fa241af8bULL;
  static const uint64_t static_value2 = 0x047640ec48eaf40fULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_define_data::grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_define_data/grasp";
  }

  static const char* value(const ::ros_define_data::grasp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_define_data::grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 x\n"
"uint16 y\n"
"float64 z\n"
"float64 angle\n"
"float64 width\n"
;
  }

  static const char* value(const ::ros_define_data::grasp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_define_data::grasp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.angle);
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grasp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_define_data::grasp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_define_data::grasp_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_DEFINE_DATA_MESSAGE_GRASP_H
